# ========== å…¨å±€æ ¼å¼ ==========
format = """
$directory$git_branch$git_status$nodejs$python
$character
"""

# ========== ç›®å½• ==========
[directory]
truncation_length = 5
truncate_to_repo = false
style = "bold cyan"
home_symbol = "~"
read_only = " ó°Œ¾"
format = "[$path]($style)[$read_only]($read_only_style) "

# ========== Git åˆ†æ”¯ ==========
[git_branch]
symbol = "î‚  "
style = "bold purple"
format = "[$symbol$branch]($style) "

# ========== Git çŠ¶æ€ ==========
[git_status]
style = "red"
format = "([$all_status$ahead_behind]($style)) "
conflicted = "âš”ï¸ "
ahead = "â‡¡${count}"
behind = "â‡£${count}"
diverged = "â‡•${ahead_count}/${behind_count}"
modified = "!"
staged = "+"
untracked = "?"
renamed = "Â»"
deleted = "âœ˜"

# ========== Node ==========
[nodejs]
symbol = "îœ˜ "
style = "green"
format = "[$symbol($version )]($style)"

# ========== Python ==========
[python]
symbol = "ğŸ "
style = "bold green"
format = "[$symbol$version ($virtualenv)]($style)"

# ========== å‘½ä»¤è€—æ—¶ ==========
[cmd_duration]
min_time = 2000
format = "â± [$duration]($style) "
style = "dimmed white"

# ========== æç¤ºç¬¦ ==========
[character]
success_symbol = "[â¯](bold green)"
error_symbol = "[â¯](bold red)"
vimcmd_symbol = "[â®](bold yellow)"
